# List all the required west modules for the application here.
# Zephyr is already included through $ZEPHYR_WS/zenv/west.yml
# file, but can be overriden here.

manifest:
  self:
    import: zephyr/west
