name: CI

on: [push]

jobs:
  build:
    name: Build/Test
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
      - name: Pull the repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup missing directories and files on the runner
        run: |
          touch ~/.gitconfig
      - name: Prepare container
        uses: devcontainers/ci@v0.3
        with:
          imageName: zenv # Local name only
          imageTag: latest # Local tag only
          push: never
      - name: Build and test presets
        uses: devcontainers/ci@v0.3
        with:
          imageName: zenv
          imageTag: latest
          push: never
          runCmd: |
            set -euo pipefail
            git fetch --tags
            git rev-parse HEAD
            git status --short
            make
            make tests RUN=1
  format:
    name: Code formatting
    runs-on: ubuntu-latest
    steps:
      - name: Pull the repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup missing directories and files on the runner
        run: |
          mkdir -p ~/.ssh
          touch ~/.gitconfig
      - name: Prepare container
        uses: devcontainers/ci@v0.3
        with:
          imageName: zenv # Local name only
          imageTag: latest # Local tag only
          push: never
      - name: Check formatting
        uses: devcontainers/ci@v0.3
        with:
          imageName: zenv
          imageTag: latest
          push: never
          runCmd: |
            make format
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
      - name: Pull the repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup missing directories and files on the runner
        run: |
          touch ~/.gitconfig
      - name: Prepare container
        uses: devcontainers/ci@v0.3
        with:
          imageName: zenv # Local name only
          imageTag: latest # Local tag only
          push: never
      - name: Run lint
        uses: devcontainers/ci@v0.3
        with:
          imageName: zenv
          imageTag: latest
          push: never
          runCmd: |
            make CHECK=1
